export let database = [
    {
      username: "user1",
      password: "pass1",
      role:"operator"
    },
    {
      username: "user2",
      password: "pass2",
      role:"admin"
    }
  ];
export let data=[
    {
    "id": "1",
    "temperature": "23 c",
    "humidity": "90%",
    "lat": 25.243143273449427,
    "lng": 55.32663345336914,
    "name": "sensor-1",
    "status": "on",
    "totalPowerConsumption": "23 kw",
   
    },
   
    {
    "id": "2",
    "temperature": "21 c",
    "humidity": "92%",
    "lat": 20,
    "lng": 57,
    "name": "sensor-2",
    "status": "off",
    "totalPowerConsumption": "22 kw",
    },
    {
        "id": "3",
        "temperature": "23 c",
        "humidity": "93%",
        "lat": 32,
        "lng": 35,
        "name": "sensor-3",
        "status": "on",
        "totalPowerConsumption": "24 kw",
       
        },
       
        {
        "id": "4",
        "temperature": "24 c",
        "humidity": "94%",
        "lat": 28,
        "lng": 79,
        "name": "sensor-4",
        "status": "off",
        "totalPowerConsumption": "25 kw",
        },
         {
            "id": "5",
            "temperature": "25 c",
            "humidity": "95%",
            "lat": 35,
            "lng": 55.32663345336914,
            "name": "sensor-5",
            "status": "on",
            "totalPowerConsumption": "26 kw",
           
            },
           
            {
            "id": "6",
            "temperature": "26 c",
            "humidity": "96%",
            "lat": 40,
            "lng": 55.37482,
            "name": "sensor-6",
            "status": "off",
            "totalPowerConsumption": "27 kw",
            },
            {
                "id": "7",
                "temperature": "27 c",
                "humidity": "97%",
                "lat": 25.243143273449427,
                "lng": 70.222,
                "name": "sensor-7",
                "status": "on",
                "totalPowerConsumption": "28 kw",
               
                },
               
                {
                "id": "8",
                "temperature": "28 c",
                "humidity": "98%",
                "lat": 10.324444,
                "lng": 55.37482,
                "name": "sensor-8",
                "status": "off",
                "totalPowerConsumption": "29 kw",
                },
                {
                    "id": "9",
                    "temperature": "29 c",
                    "humidity": "99%",
                    "lat": 25.2431,
                    "lng": 64.22222,
                    "name": "sensor-9",
                    "status": "on",
                    "totalPowerConsumption": "29 kw",
                   
                    },
                   
                    {
                    "id": "10",
                    "temperature": "30 c",
                    "humidity": "92%",
                    "lat": 37,
                    "lng": 80.2222,
                    "name": "sensor-10",
                    "status": "off",
                    "totalPowerConsumption": "29 kw",
                    },
                    {
                        "id": "11",
                        "temperature": "23 c",
                        "humidity": "90%",
                        "lat": 40.22222,
                        "lng": 70.2222,
                        "name": "sensor-11",
                        "status": "on",
                        "totalPowerConsumption": "23 kw",
                       
                        },
];
 export let Device_details_object=
[
 {
 "id": "1",
 "lat": 25.243143273449427,
 "lng": 55.32663345336914,
 "name": "sensor-1",
 "status": "on",
 "temperature": "23 c",
 "humidity": "90%",
 "totalPowerConsumption": "23 kw",
 "totalPowerConsumptionpermonth": {
 "jan" : "24 kw",
 "feb" : "21 kw",
 "march" : "22 kw",
 "april" : "28 kw",
"may" : "29 kw",
 "june" : "31 kw",
 "july" : "34 kw",
 "august" : "23 kw",
"september" : "24 kw",
 "october": "41 kw",
"november": "24 kw",
 "december" : "21 kw",
}
 }
,
{
    "id": "2",
    "temperature": "21 c",
    "humidity": "92%",
    "lat": 20,
    "lng": 57,
    "name": "sensor-2",
    "status": "off",
    "totalPowerConsumption": "22 kw",
    "totalPowerConsumptionpermonth": {
        "jan" : "24 kw",
        "feb" : "21 kw",
        "march" : "22 kw",
        "april" : "28 kw",
       "may" : "29 kw",
        "june" : "31 kw",
        "july" : "34 kw",
        "august" : "23 kw",
       "september" : "24 kw",
        "october": "41 kw",
       "november": "24 kw",
        "december" : "21 kw",
       }
    },
    {
        "id": "3",
        "temperature": "23 c",
        "humidity": "93%",
        "lat": 32,
        "lng": 35,
        "name": "sensor-3",
        "status": "on",
        "totalPowerConsumption": "24 kw",
        "totalPowerConsumptionpermonth": {
            "jan" : "24 kw",
            "feb" : "21 kw",
            "march" : "22 kw",
            "april" : "28 kw",
           "may" : "29 kw",
            "june" : "31 kw",
            "july" : "34 kw",
            "august" : "23 kw",
           "september" : "24 kw",
            "october": "41 kw",
           "november": "24 kw",
            "december" : "21 kw",
           }
       
        },
       
        {
        "id": "4",
        "temperature": "24 c",
        "humidity": "94%",
        "lat": 28,
        "lng": 79,
        "name": "sensor-4",
        "status": "off",
        "totalPowerConsumption": "25 kw",
        "totalPowerConsumptionpermonth": {
            "jan" : "24 kw",
            "feb" : "21 kw",
            "march" : "22 kw",
            "april" : "28 kw",
           "may" : "29 kw",
            "june" : "31 kw",
            "july" : "34 kw",
            "august" : "23 kw",
           "september" : "24 kw",
            "october": "41 kw",
           "november": "24 kw",
            "december" : "21 kw",
           }
        },
         {
            "id": "5",
            "temperature": "25 c",
            "humidity": "95%",
            "lat": 35,
            "lng": 55.32663345336914,
            "name": "sensor-5",
            "status": "on",
            "totalPowerConsumption": "26 kw",
            "totalPowerConsumptionpermonth": {
                "jan" : "24 kw",
                "feb" : "21 kw",
                "march" : "22 kw",
                "april" : "28 kw",
               "may" : "29 kw",
                "june" : "31 kw",
                "july" : "34 kw",
                "august" : "23 kw",
               "september" : "24 kw",
                "october": "41 kw",
               "november": "24 kw",
                "december" : "21 kw",
               }
           
            },
           
            {
            "id": "6",
            "temperature": "26 c",
            "humidity": "96%",
            "lat": 40,
            "lng": 55.37482,
            "name": "sensor-6",
            "status": "off",
            "totalPowerConsumption": "27 kw",
            "totalPowerConsumptionpermonth": {
                "jan" : "24 kw",
                "feb" : "21 kw",
                "march" : "22 kw",
                "april" : "28 kw",
               "may" : "29 kw",
                "june" : "31 kw",
                "july" : "34 kw",
                "august" : "23 kw",
               "september" : "24 kw",
                "october": "41 kw",
               "november": "24 kw",
                "december" : "21 kw",
               }
            },
            {
                "id": "7",
                "temperature": "27 c",
                "humidity": "97%",
                "lat": 25.243143273449427,
                "lng": 70.222,
                "name": "sensor-7",
                "status": "on",
                "totalPowerConsumption": "28 kw",
                "totalPowerConsumptionpermonth": {
                    "jan" : "24 kw",
                    "feb" : "21 kw",
                    "march" : "22 kw",
                    "april" : "28 kw",
                   "may" : "29 kw",
                    "june" : "31 kw",
                    "july" : "34 kw",
                    "august" : "23 kw",
                   "september" : "24 kw",
                    "october": "41 kw",
                   "november": "24 kw",
                    "december" : "21 kw",
                   }
                },
               
                {
                "id": "8",
                "temperature": "28 c",
                "humidity": "98%",
                "lat": 10.324444,
                "lng": 55.37482,
                "name": "sensor-8",
                "status": "off",
                "totalPowerConsumption": "29 kw",
                "totalPowerConsumptionpermonth": {
                    "jan" : "24 kw",
                    "feb" : "21 kw",
                    "march" : "22 kw",
                    "april" : "28 kw",
                   "may" : "29 kw",
                    "june" : "31 kw",
                    "july" : "34 kw",
                    "august" : "23 kw",
                   "september" : "24 kw",
                    "october": "41 kw",
                   "november": "24 kw",
                    "december" : "21 kw",
                   }
                },
                {
                    "id": "9",
                    "temperature": "29 c",
                    "humidity": "99%",
                    "lat": 25.2431,
                    "lng": 64.22222,
                    "name": "sensor-9",
                    "status": "on",
                    "totalPowerConsumption": "29 kw",
                    "totalPowerConsumptionpermonth": {
                        "jan" : "24 kw",
                        "feb" : "21 kw",
                        "march" : "22 kw",
                        "april" : "28 kw",
                       "may" : "29 kw",
                        "june" : "31 kw",
                        "july" : "34 kw",
                        "august" : "23 kw",
                       "september" : "24 kw",
                        "october": "41 kw",
                       "november": "24 kw",
                        "december" : "21 kw",
                       }
                   
                    },
                   
                    {
                    "id": "10",
                    "temperature": "30 c",
                    "humidity": "92%",
                    "lat": 37,
                    "lng": 80.2222,
                    "name": "sensor-10",
                    "status": "off",
                    "totalPowerConsumption": "29 kw",
                    "totalPowerConsumptionpermonth": {
                        "jan" : "24 kw",
                        "feb" : "21 kw",
                        "march" : "22 kw",
                        "april" : "28 kw",
                       "may" : "29 kw",
                        "june" : "31 kw",
                        "july" : "34 kw",
                        "august" : "23 kw",
                       "september" : "24 kw",
                        "october": "41 kw",
                       "november": "24 kw",
                        "december" : "21 kw",
                       }
                    },
                    {
                        "id": "11",
                        "temperature": "23 c",
                        "humidity": "90%",
                        "lat": 40.22222,
                        "lng": 70.2222,
                        "name": "sensor-11",
                        "status": "on",
                        "totalPowerConsumption": "23 kw",
                        "totalPowerConsumptionpermonth": {
                            "jan" : "24 kw",
                            "feb" : "21 kw",
                            "march" : "22 kw",
                            "april" : "28 kw",
                           "may" : "29 kw",
                            "june" : "31 kw",
                            "july" : "34 kw",
                            "august" : "23 kw",
                           "september" : "24 kw",
                            "october": "41 kw",
                           "november": "24 kw",
                            "december" : "21 kw",
                           }
                       
                        }
]